### PR TITLE
Feature/auto refresh

### PR DESCRIPTION
**Pull request by pgalasti**
Added some functionality for the program to clear display and re-fetch/output with latest quotes. This will allow user to run the program and leave the terminal open as it updates until user kills. May eat away at IEXCloud credits though.

I tested with relevant flags but may have missed something.  If you think this feature is relevant to the base app, let me know if there's anything you'd like cleaned up/different.

### CODE REVIEW

**Comment by frossm** [comment]
Hello pgalasti.  You appear to be a better Java programmer than I am!  Thank you for your pull request.  Great idea for an enhancement.  Let me take a detailed look at it.

However, I did take a quick look at it, and I'd add a time in seconds option after the `-a`.  Maybe it can default to 30sec if there is none given (although that seems like a very fast fresh time.)

Secondly, you should add the `-a TIME` to the help file.

Regardless, I'll get back to you.

Thanks,

Michael

**Comment by pgalasti** [comment]
Sure, sounds good! I'll write up some changes to make it a variable time. Thanks.

**Comment by pgalasti** [comment]
I went ahead and made the parameter require a time from the user. I'd like to make sure they're in control of how many IEX credits they're using :)

**Comment by frossm** [comment]
Thanks for the pull request pgalasti.  I've merged it into master.  The snap is building and I'll do a new quoter release shortly.  Shoot - just released I forgot to update the version.

**Comment by pgalasti** [comment]
Great, happy to contribute. Love the app, I use it daily.

**Comment by frossm** [comment]
Hello pgalasti.  Just another note of thanks.  Since I've removed the API calls and just screen scrape everything, I've been using the `-a` autorefresh during the day.  It's great.  Thank you.

**Comment by pgalasti** [comment]
Awesome, glad to hear it. I need to check out the latest on my Linux box
when I get a chance.

**Pull request merged**
